### ISSUE TITLE
Feature request: 16k

### ISSUE THREAD

**Issue by Redd56** [EVAST9919/yoso-version-tracker#13]
Thats it, just the ability for 16keys, some adofai maps are only doable with 16 keys

**Comment by EVAST9919** [comment]
Adding support for this isn't an issue, but how you are going to use them all at the same time? I can imagine 10 keys = 10 fingers but more?

**Comment by Redd56** [comment]
Multiple keys per finger, and some chaotic people use 2 keys per foot cause 16k is actualy hard

**Comment by Redd56** [comment]
also some songs like the full version of xultor cry, are only possible due to 16k

**Comment by Redd56** [comment]
i mean 8k is theoreticly possible but you have to vibro pretty damn fast

**Comment by EVAST9919** [comment]
Okay, I see

**Comment by EVAST9919** [comment]
Added in the next release
