### ISSUE TITLE
Glitch shader isn't compiling on some linux machines

### ISSUE THREAD

**Issue by Redd56** [EVAST9919/yoso-version-tracker#14]
https://user-images.githubusercontent.com/12189828/192066154-9a2181b0-160b-4c3a-9c1c-df8f86e044ba.mp4

 [this is the map](https://steamcommunity.com/sharedfiles/filedetails/?id=2124854584)

**Comment by Redd56** [comment]
[runtime.log](https://github.com/EVAST9919/yoso-version-tracker/files/9637396/runtime.log)

**Comment by EVAST9919** [comment]
Fixed in the latest release
