### ISSUE TITLE
Playing before the end of a pause

### ISSUE THREAD

**Issue by Terochi** [EVAST9919/yoso-version-tracker#15]
The video should speak for itself.
https://user-images.githubusercontent.com/100224757/197767929-e878f5fb-b034-4d87-8c07-5df5f53eea51.mp4

Fix by disabling input in the pause or visually stop the movement and resume when the note should've been hit.

**Comment by EVAST9919** [comment]
It's not a pause overlay, it's a break time indicator. And it's expected that you can hit notes during break time as seen in some 2b osu maps where the whole map in a "break state'
