### ISSUE TITLE
Replays are no longer supported

### ISSUE THREAD

**Issue by Halozhan** [EVAST9919/yoso-version-tracker#2]
![image](https://user-images.githubusercontent.com/25768818/151402843-f321e9fc-1702-4f2f-8418-1c237995e933.png)

**Comment by EVAST9919** [comment]
Okay, this one is osu-side.
When trying to load replay - lazer searches for a ruleset with the same id as the score has. But after this update every custom ruleset has the same id, which is -1.
Not closing since this may be fixed later.

**Comment by EVAST9919** [comment]
Tracking here https://github.com/ppy/osu/issues/17350

**Comment by EVAST9919** [comment]
Closing because replays for custom rulesets are completely disabled osu-side

**Comment by Redd56** [comment]
Rip replaya
